loaderVersion="[38,)"
license="LGPL-3.0"
issueTrackerURL="https://github.com/UnifyCraft/UniCore/issues"
[[mods]]
    modId="${mod_id}"
    version="${mod_version}"
    displayName="${mod_name}"
    authors="UnifyCraft Team"
    description="Core library and Minecraft experience."