loaderVersion="[38,)"
license="LGPL-3.0"
issueTrackerURL="https://github.com/UnifyCraft/UniCore/issues"
[[mods]]
    modId="${id}"
    version="${version}"
    displayName="${name}"
    authors="UnifyCraft Team"
    description="Core library and Minecraft experience."